---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# northstar

<!-- badges: start -->
<!-- badges: end -->

The goal of **northstar** is to ...

## Installation

You can install the development version of **northstar** from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("andrewallenbruce/northstar")
```

## Example

```{r example}
library(northstar)
```


```{r}
rvu() |> 
  dplyr::filter(status == "A", 
                work.rvu == max(work.rvu, na.rm = TRUE)) |> 
  dplyr::select(hcpcs, 
                description,
                work.rvu, 
                pe.rvu_nonfac, 
                pe.rvu_fac, 
                mp.rvu, 
                cf) |>
  dplyr::glimpse()
```

```{r}
gpci() |> 
  dplyr::filter(state == "GA", 
                locality == "01") |>
  dplyr::glimpse()
```

```{r}
par <- northstar:::calc_payment(
  wk.rvu  = 108.91,
  pe.rvu  = 35.14,
  mp.rvu  = 26.95,
  wk.gpci = 1.0,
  pe.gpci = 0.997,
  mp.gpci = 1.128,
  cf      = 32.7442)

nonpar <- par * 0.95
```

```{r}
pp <- function(par    = par, 
               nonpar = nonpar, 
               lc     = limiting_charge(par)) {
  
  glue::glue("Participating Amount:    {gt::vec_fmt_currency(par)}\n",  
             "Non-Particpating Amount: {gt::vec_fmt_currency(nonpar)}\n", 
             "Limiting Charge:         {gt::vec_fmt_currency(lc)}",
             par = par, 
             nonpar = nonpar, 
             lc = lc)
}

pp(par, 
   nonpar, 
   limiting_charge(par))
```

```{r}
payment() |> 
  dplyr::filter(hcpcs == "39503", 
                carrier_no == "10212",
                locality == "01") |> 
  dplyr::glimpse()
```
