---
title: "Fee Schedule"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Fee Schedule}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse  = FALSE,
  echo      = TRUE,
  message   = FALSE, 
  warning   = FALSE,
  error     = TRUE,
  comment   = "#>",
  dpi       = 600, 
  out.width = "100%"
  )

library(northstar)
library(dplyr)
library(tidyr)
library(purrr)
library(janitor)
library(gt)
```

# HCPCS

```{r}
hcpcs_search(
  hcpcs    = "39503", 
  state    = "GA", 
  locality = "99",
  mac      = "10212") |> 
  remove_empty(which = c("rows", "cols")) |>
  rowwise() |>
  mutate(descriptions_clinician = map(
    descriptions_clinician, ~paste0("* ", ., collapse = "\n"))) |>
  unnest(cols = descriptions_clinician) |>
  ungroup() |> 
  case_multproc(mult_proc) |>
  case_global(global) |>
  case_cosurg(surg_co) |>
  case_assistant(surg_asst) |>
  case_status(status) |>
  case_supervision(supvis) |>
  case_bilateral(surg_bilat) |>
  case_team(surg_team) |>
  case_imaging(dximg) |>
  case_pctc(pctc) |>
  case_opps(opps) |>
  case_chapter_cpt(hcpcs) |> 
  case_category(hcpcs) |>
  rename(CPT = hcpcs,
         Description = description,
         Consumer = description_consumer,
         Clinician = descriptions_clinician,
         Chapter = chapter,
         Range = range,
         # RBCS = rbcs,
         Status = status,
         MAC = mac,
         State = state,
         Locality = locality,
         Area = area,
         Counties = counties,
         "Work GPCI" = wgpci,
         "Practice GPCI" = pgpci,
         "Malpractice GPCI" = mgpci,
         "Work RVU" = wrvu,
         "Non-Facility Practice RVU" = nfprvu,
         "Facility Practice RVU" = fprvu,
         "Malpractice RVU" = mrvu,
         "Conversion Factor" = cf,
         "Total Facility RVUs" = frvus,
         "Total Non-Facility RVUs" = nrvus,
         "Facility PAR Fee" = fpar,
         "Non-Facility PAR Fee" = npar,
         "Facility NON-PAR Fee" = fnpar,
         "Non-Facility NON-PAR Fee" = nfnpar,
         "Facility Limiting Charge" = flim,
         "Non-Facility Limiting Charge" = nlim,
         "Multiple Procedures" = mproc_description,
         "Global Days" = global_description,
         "Preoperative" = op_pre,
         "Intraoperative" = op_intra,
         "Postoperative" = op_post,
         "Assistant at Surgery" = asst_description,
         "Co-Surgeons" = cosurg_description,
         ) |>
  display_long() |>
  gt(rowname_col = "name") |>
  gt_style(tablign = "right", tabsize = 16, tabwt = "bold") |> 
  sub_missing(missing_text = "Concept Does Not Apply") |> 
  fmt_markdown()
```


```{r echo=FALSE, eval=FALSE}
hcpcs_search(hcpcs    = "70170", 
             state    = "GA", 
             locality = "01") |> 
  glimpse()
```


# ICD-10-CM

```{r}
icd10cm(code = "F50.82") |> 
  select("ICD-10-Code" = code, 
         Description = description, 
         Section = section,
         "Ch. No." = ch,
         Chapter = chapter, 
         Range = range, 
         Abbreviation = abbrev) |> 
  display_long() |>
  gt(rowname_col = "name") |>
  gt_style(tablign = "right", tabsize = 16, tabwt = "bold")
```

