---
title: "Fee Schedule"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Fee Schedule}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse  = FALSE,
  echo      = TRUE,
  message   = TRUE, 
  warning   = FALSE,
  error     = TRUE,
  comment   = "#>",
  dpi       = 600, 
  out.width = "100%"
  )
```

```{r setup, message=FALSE, warning=FALSE}
library(northstar)
library(dplyr)
library(tidyr)
library(purrr)
library(janitor)
library(gt)
```

## Look Up HCPCS Code

```{r}
hcpcs_search(
  hcpcs    = "39503", 
  state    = "GA", 
  locality = "99",
  mac      = "10212") |> 
  remove_empty(which = c("rows", "cols")) |>
  rowwise() |>
  mutate(description_clinician = map(description_clinician, ~paste0("* ", ., collapse = "\n"))) |>
  unnest(cols = description_clinician) |>
  ungroup() |> 
  northstar:::display_long() |>
  gt() |>
  fmt_markdown() |> 
  tab_options(
    column_labels.hidden = TRUE,
    table.width = pct(75),
    heading.title.font.size = px(20),
    heading.subtitle.font.size = px(14),
    heading.align = "left",
    footnotes.font.size = px(12))
```


```{r}
opps(hcpcs    = "70170", 
     mac      = "10212", 
     locality = "01") |> 
  glimpse()
```


```{r}
hcpcs_search(hcpcs    = "70170", 
             state    = "GA", 
             locality = "01") |> 
  glimpse()
```


## Data Sources

```{r}
rvu(hcpcs = "11646") |> 
  glimpse()
```

```{r}
gpci(state    = "GA",
     locality = "01",
     mac      = "10212") |> 
  glimpse()
```

```{r}
pfs(hcpcs    = "11646", 
    locality = "01",
    mac      = "10212") |> 
  glimpse()
```


```{r}
descriptors(hcpcs = "11646") |> 
  glimpse()
```



```{r}
level2(hcpcs = "V5299") |> glimpse()
```

```{r}
rbcs(hcpcs = "V5299") |> glimpse()
```

