# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <hcpcs_search>
  "cf",
  # <hcpcs_search>
  "clinician_descriptor",
  # <hcpcs_search>
  "cpt",
  # <col_lb>
  "description",
  # <hcpcs_search>
  "fpar",
  # <hcpcs_search>
  "fprvu",
  # <col_lb>
  "label",
  # <rbcs>
  "major",
  # <hcpcs_search>
  "mgpci",
  # <hcpcs_search>
  "mod",
  # <hcpcs_search>
  "mrvu",
  # <hcpcs_search>
  "npar",
  # <hcpcs_search>
  "nprvu",
  # <hcpcs_search>
  "pgpci",
  # <hcpcs_search>
  "status",
  # <col_lb>
  "var",
  # <hcpcs_search>
  "wgpci",
  # <hcpcs_search>
  "wrvu",
  NULL
))
