# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <status_codes>
  "code",
  # <calc_amounts_df>
  "fpar",
  # <calc_amounts_df>
  "fprvu",
  # <calc_amounts_df>
  "mgpci",
  # <calc_amounts_df>
  "mod",
  # <calc_amounts_df>
  "mrvu",
  # <calc_amounts_df>
  "npar",
  # <calc_amounts_df>
  "nprvu",
  # <calc_amounts_df>
  "pgpci",
  # <abb2full>
  "state.abb",
  # <abb2full>
  "state.name",
  # <calc_amounts_df>
  "status",
  # <calc_amounts_df>
  "wgpci",
  # <calc_amounts_df>
  "wrvu",
  # <abb2full>
  "x",
  # <abb2full>
  "y",
  NULL
))
