# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <calculate_amounts>
  "facility",
  # <calculate_amounts>
  "nonfacility",
  # <get_ptp_edits>
  "ptp_deleted",
  # <search_rbcs>
  "rbcs_category",
  # <search_rbcs>
  "rbcs_family",
  # <search_rbcs>
  "rbcs_procedure",
  # <search_rbcs>
  "rbcs_subcategory",
  NULL
))
